//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online.Payment.Ghabz.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ghabzHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ghabzHistory()
        {
            this.paymentHistories = new HashSet<paymentHistory>();
        }
    
        public long Id { get; set; }
        public string ShenaseGhabz { get; set; }
        public string ShenasePardakht { get; set; }
        public int Price { get; set; }
        public string Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<paymentHistory> paymentHistories { get; set; }
    }
}
