//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online.Payment.Ghabz.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class paymentHistory
    {
        public long Id { get; set; }
        public bool IsPayment { get; set; }
        public string TrakingNumber { get; set; }
        public Nullable<long> GhabzHistoryId { get; set; }
    
        public virtual ghabzHistory ghabzHistory { get; set; }
    }
}
